fix build error: ‘novatel_custom_init’ defined but not used
libtool: link: ranlib .libs/libmm-plugin-motorola.a
libtool: link: ( cd ".libs" && rm -f "libmm-plugin-motorola.la" && ln -s
"../libmm-plugin-motorola.la" "libmm-plugin-motorola.la" )
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.
-I..  -pthread -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0
-I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gudev-1.0
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
-I.. -I../src -I../src -I../include -I../include -I../libmm-glib
-I../libmm-glib/generated -I../libmm-glib/generated -pthread
-I/usr/include/libqmi-glib -I/usr/include/glib-2.0
-I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread
-I/usr/include/libmbim-glib -I/usr/include/glib-2.0
-I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../plugins/novatel
-Wall -Werror -std=gnu89 -g -O2 -Wmissing-declarations
-Wmissing-prototypes -Wdeclaration-after-statement -Wno-unused-parameter
-Wno-sign-compare -fno-strict-aliasing -Wno-deprecated-declarations
-Wno-unused-but-set-variable -Wformat-security -c -o
novatel/libmm_plugin_novatel_la-mm-plugin-novatel.lo `test -f
'novatel/mm-plugin-novatel.c' || echo './'`novatel/mm-plugin-novatel.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -pthread
-I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0
-I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gudev-1.0
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
-I.. -I../src -I../src -I../include -I../include -I../libmm-glib
-I../libmm-glib/generated -I../libmm-glib/generated -pthread
-I/usr/include/libqmi-glib -I/usr/include/glib-2.0
-I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread
-I/usr/include/libmbim-glib -I/usr/include/glib-2.0
-I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../plugins/novatel -Wall
-Werror -std=gnu89 -g -O2 -Wmissing-declarations -Wmissing-prototypes
-Wdeclaration-after-statement -Wno-unused-parameter -Wno-sign-compare
-fno-strict-aliasing -Wno-deprecated-declarations
-Wno-unused-but-set-variable -Wformat-security -c
novatel/mm-plugin-novatel.c  -fPIC -DPIC -o
novatel/.libs/libmm_plugin_novatel_la-mm-plugin-novatel.o
novatel/mm-plugin-novatel.c:71:1: error: ‘novatel_custom_init_finish’
defined but not used [-Werror=unused-function]
 novatel_custom_init_finish (MMPortProbe *probe,
 ^
novatel/mm-plugin-novatel.c:164:1: error: ‘novatel_custom_init’ defined
but not used [-Werror=unused-function]
 novatel_custom_init (MMPortProbe *probe,
 ^
cc1: all warnings being treated as errors